version: "3.8"

services: 
    mssql-db:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - "1433:1433"
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "super_user_123"
        volumes:
            - mssql-db-data:/var/opt/mssql/data

volumes:
    mssql-db-data: